[platformio]
src_dir = .

[env:nucleo_f411re]
platform = ststm32
board = nucleo_f411re
framework = stm32cube
lib_archive = no
monitor_speed = 115200
build_src_filter =
    +<src/*.c>
    +<Common/*.c>
    +<Common/framework_files/*.c>
build_flags =
    -Wl,-u,_printf_float,-u,_scanf_float
    -lm
    -DSTM32F4
    -DHSE_VALUE=8000000U
    -ICommon
    -ICommon/framework_files
